gem 'minitest', '~> 5.2'
require 'minitest/autorun'
require 'minitest/pride'
require 'bigdecimal'
require 'pry'

#require '../lib/item'
#require '../lib/merchant'
#require '../lib/merchant_repository'
#require '../lib/item_repository'
