gem 'minitest', '~> 5.2'
require 'minitest/autorun'
require 'minitest/pride'
require 'bigdecimal'
require 'pry'

require './lib/item'
require './lib/merchant'
require './lib/invoice'
require './lib/item_repository'
require './lib/merchant_repository'
require './lib/invoice_repository'
require './lib/sales_engine'
require './lib/sales_analyst'
